import antfu from '@antfu/eslint-config'
import blueprintPlugin from '@blueprintjs/eslint-plugin'
import pluginRouter from '@tanstack/eslint-plugin-router'
import reactCompiler from 'eslint-plugin-react-compiler'

export default antfu(
  {
    react: true,
    typescript: true,
    gitignore: false,
    formatters: {
      css: true,
    },
    ignores: [
      // Auto-generated by TanStack Router CLI — never edit manually
      'src/routeTree.gen.ts',
    ],
  },
  // Blueprint — enforce component usage and ban deprecated APIs
  blueprintPlugin.flatConfigs.recommended,
  // TanStack Router — route property ordering + param naming
  ...pluginRouter.configs['flat/recommended'],
  // TanStack route files always export both a route object and a component —
  // react-refresh false-positives on this pattern
  {
    files: ['src/routes/**/*.tsx'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
  // React Compiler — flags Rules of React violations that block auto-memoization
  {
    plugins: { 'react-compiler': reactCompiler },
    rules: { 'react-compiler/react-compiler': 'error' },
  },
  // Blueprint icon usage rules — enforce tree-shaken icon components
  {
    rules: {
      'no-restricted-syntax': [
        'error',
        // Ban icon name strings — Blueprint loads both 16px and 20px chunks lazily
        // for string names, which is not tree-shakeable. Use a component instead.
        {
          selector: 'JSXAttribute[name.name=/^(icon|leftIcon|rightIcon)$/][value.type=\'Literal\']',
          message: 'Use a Blueprint icon component from @blueprintjs/icons (e.g. leftIcon={<Search />}) or a Tabler component in leftElement/rightElement. String names load all icons lazily and are not tree-shakeable.',
        },
        // Ban Tabler icons in leftIcon/rightIcon — Blueprint wraps these props through
        // <Icon> which causes layout issues (icon floats outside the input boundary).
        // Use a Blueprint icon component for leftIcon/rightIcon, or leftElement/rightElement for Tabler.
        {
          selector: 'JSXAttribute[name.name=/^(leftIcon|rightIcon)$/] JSXOpeningElement[name.name=/^Icon[A-Z]/]',
          message: 'Tabler icons cannot be used in leftIcon/rightIcon — Blueprint routes these through <Icon> and layout breaks. Use a Blueprint icon component (e.g. leftIcon={<Search />}) or move the Tabler icon to leftElement/rightElement.',
        },
        // Ban non-tree-shakeable @blueprintjs/icons barrel exports — these pull in all
        // SVG path data for every icon in a single chunk.
        {
          selector: 'ImportDeclaration[source.value=\'@blueprintjs/icons\'] > ImportSpecifier[imported.name=/^(IconSvgPaths16|IconSvgPaths20|getIconPaths|allPaths)$/]',
          message: 'IconSvgPaths16/20, getIconPaths, and allPaths load every icon path into one chunk — defeats tree-shaking. Import individual icon components: import { Search } from \'@blueprintjs/icons\'.',
        },
        // Enforce Jotai atom naming convention — atoms must use the *Atom suffix
        {
          selector: 'VariableDeclarator[init.type=\'CallExpression\'][init.callee.name=/^atom/]:not([id.name=/.+Atom$/])',
          message: 'Jotai atoms must use the *Atom naming convention (e.g., viewModeAtom, not viewMode).',
        },
        // Ban atomFamily — broken with React Compiler (infinite re-render)
        {
          selector: 'CallExpression[callee.name=\'atomFamily\']',
          message: 'atomFamily is broken with React Compiler. Use static atoms instead.',
        },
      ],
    },
  },
)
