import antfu from '@antfu/eslint-config'
import blueprintPlugin from '@blueprintjs/eslint-plugin'
import pluginRouter from '@tanstack/eslint-plugin-router'
import reactCompiler from 'eslint-plugin-react-compiler'

export default antfu(
  {
    react: true,
    typescript: true,
    gitignore: false,
    formatters: {
      css: true,
    },
    ignores: [
      // Auto-generated by TanStack Router CLI — never edit manually
      'src/routeTree.gen.ts',
    ],
  },
  // Blueprint — enforce component usage and ban deprecated APIs
  blueprintPlugin.flatConfigs.recommended,
  // TanStack Router — route property ordering + param naming
  ...pluginRouter.configs['flat/recommended'],
  // TanStack route files always export both a route object and a component —
  // react-refresh false-positives on this pattern
  {
    files: ['src/routes/**/*.tsx'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
  // React Compiler — flags Rules of React violations that block auto-memoization
  {
    plugins: { 'react-compiler': reactCompiler },
    rules: { 'react-compiler/react-compiler': 'error' },
  },
)
