packages:
  - "apps/*"
  - "packages/*"
disallowWorkspaceCycles: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.1.14
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.14
  vite-plus: 0.1.14
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
    - esbuild
  allowedVersions:
    vite: "*"
    vitest: "*"
    esbuild: "*"
    typescript: "6"
    react: "19"
    react-dom: "19"
    "@types/react": "19"
