/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ContentRouteImport } from './routes/_content'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ContentSearchRouteImport } from './routes/_content/search'
import { Route as ContentGuidesIndexRouteImport } from './routes/_content/guides/index'
import { Route as ContentDocsIndexRouteImport } from './routes/_content/docs/index'
import { Route as ContentBlogIndexRouteImport } from './routes/_content/blog/index'
import { Route as ContentBlocksIndexRouteImport } from './routes/_content/blocks/index'
import { Route as ContentGuidesSlugRouteImport } from './routes/_content/guides/$slug'
import { Route as ContentDocsSplatRouteImport } from './routes/_content/docs/$'
import { Route as ContentBlogSlugRouteImport } from './routes/_content/blog/$slug'
import { Route as ContentBlocksSlugRouteImport } from './routes/_content/blocks/$slug'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/_content',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ContentSearchRoute = ContentSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ContentRoute,
} as any)
const ContentGuidesIndexRoute = ContentGuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => ContentRoute,
} as any)
const ContentDocsIndexRoute = ContentDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => ContentRoute,
} as any)
const ContentBlogIndexRoute = ContentBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => ContentRoute,
} as any)
const ContentBlocksIndexRoute = ContentBlocksIndexRouteImport.update({
  id: '/blocks/',
  path: '/blocks/',
  getParentRoute: () => ContentRoute,
} as any)
const ContentGuidesSlugRoute = ContentGuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => ContentRoute,
} as any)
const ContentDocsSplatRoute = ContentDocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => ContentRoute,
} as any)
const ContentBlogSlugRoute = ContentBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => ContentRoute,
} as any)
const ContentBlocksSlugRoute = ContentBlocksSlugRouteImport.update({
  id: '/blocks/$slug',
  path: '/blocks/$slug',
  getParentRoute: () => ContentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/search': typeof ContentSearchRoute
  '/settings': typeof ProtectedSettingsRoute
  '/blocks/$slug': typeof ContentBlocksSlugRoute
  '/blog/$slug': typeof ContentBlogSlugRoute
  '/docs/$': typeof ContentDocsSplatRoute
  '/guides/$slug': typeof ContentGuidesSlugRoute
  '/blocks/': typeof ContentBlocksIndexRoute
  '/blog/': typeof ContentBlogIndexRoute
  '/docs/': typeof ContentDocsIndexRoute
  '/guides/': typeof ContentGuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/search': typeof ContentSearchRoute
  '/settings': typeof ProtectedSettingsRoute
  '/blocks/$slug': typeof ContentBlocksSlugRoute
  '/blog/$slug': typeof ContentBlogSlugRoute
  '/docs/$': typeof ContentDocsSplatRoute
  '/guides/$slug': typeof ContentGuidesSlugRoute
  '/blocks': typeof ContentBlocksIndexRoute
  '/blog': typeof ContentBlogIndexRoute
  '/docs': typeof ContentDocsIndexRoute
  '/guides': typeof ContentGuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_content': typeof ContentRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_content/search': typeof ContentSearchRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_content/blocks/$slug': typeof ContentBlocksSlugRoute
  '/_content/blog/$slug': typeof ContentBlogSlugRoute
  '/_content/docs/$': typeof ContentDocsSplatRoute
  '/_content/guides/$slug': typeof ContentGuidesSlugRoute
  '/_content/blocks/': typeof ContentBlocksIndexRoute
  '/_content/blog/': typeof ContentBlogIndexRoute
  '/_content/docs/': typeof ContentDocsIndexRoute
  '/_content/guides/': typeof ContentGuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/search'
    | '/settings'
    | '/blocks/$slug'
    | '/blog/$slug'
    | '/docs/$'
    | '/guides/$slug'
    | '/blocks/'
    | '/blog/'
    | '/docs/'
    | '/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/search'
    | '/settings'
    | '/blocks/$slug'
    | '/blog/$slug'
    | '/docs/$'
    | '/guides/$slug'
    | '/blocks'
    | '/blog'
    | '/docs'
    | '/guides'
  id:
    | '__root__'
    | '/'
    | '/_content'
    | '/_protected'
    | '/sign-in'
    | '/sign-up'
    | '/_content/search'
    | '/_protected/settings'
    | '/_content/blocks/$slug'
    | '/_content/blog/$slug'
    | '/_content/docs/$'
    | '/_content/guides/$slug'
    | '/_content/blocks/'
    | '/_content/blog/'
    | '/_content/docs/'
    | '/_content/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentRoute: typeof ContentRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_content': {
      id: '/_content'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_content/search': {
      id: '/_content/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ContentSearchRouteImport
      parentRoute: typeof ContentRoute
    }
    '/_content/guides/': {
      id: '/_content/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof ContentGuidesIndexRouteImport
      parentRoute: typeof ContentRoute
    }
    '/_content/docs/': {
      id: '/_content/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof ContentDocsIndexRouteImport
      parentRoute: typeof ContentRoute
    }
    '/_content/blog/': {
      id: '/_content/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof ContentBlogIndexRouteImport
      parentRoute: typeof ContentRoute
    }
    '/_content/blocks/': {
      id: '/_content/blocks/'
      path: '/blocks'
      fullPath: '/blocks/'
      preLoaderRoute: typeof ContentBlocksIndexRouteImport
      parentRoute: typeof ContentRoute
    }
    '/_content/guides/$slug': {
      id: '/_content/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof ContentGuidesSlugRouteImport
      parentRoute: typeof ContentRoute
    }
    '/_content/docs/$': {
      id: '/_content/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof ContentDocsSplatRouteImport
      parentRoute: typeof ContentRoute
    }
    '/_content/blog/$slug': {
      id: '/_content/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof ContentBlogSlugRouteImport
      parentRoute: typeof ContentRoute
    }
    '/_content/blocks/$slug': {
      id: '/_content/blocks/$slug'
      path: '/blocks/$slug'
      fullPath: '/blocks/$slug'
      preLoaderRoute: typeof ContentBlocksSlugRouteImport
      parentRoute: typeof ContentRoute
    }
  }
}

interface ContentRouteChildren {
  ContentSearchRoute: typeof ContentSearchRoute
  ContentBlocksSlugRoute: typeof ContentBlocksSlugRoute
  ContentBlogSlugRoute: typeof ContentBlogSlugRoute
  ContentDocsSplatRoute: typeof ContentDocsSplatRoute
  ContentGuidesSlugRoute: typeof ContentGuidesSlugRoute
  ContentBlocksIndexRoute: typeof ContentBlocksIndexRoute
  ContentBlogIndexRoute: typeof ContentBlogIndexRoute
  ContentDocsIndexRoute: typeof ContentDocsIndexRoute
  ContentGuidesIndexRoute: typeof ContentGuidesIndexRoute
}

const ContentRouteChildren: ContentRouteChildren = {
  ContentSearchRoute: ContentSearchRoute,
  ContentBlocksSlugRoute: ContentBlocksSlugRoute,
  ContentBlogSlugRoute: ContentBlogSlugRoute,
  ContentDocsSplatRoute: ContentDocsSplatRoute,
  ContentGuidesSlugRoute: ContentGuidesSlugRoute,
  ContentBlocksIndexRoute: ContentBlocksIndexRoute,
  ContentBlogIndexRoute: ContentBlogIndexRoute,
  ContentDocsIndexRoute: ContentDocsIndexRoute,
  ContentGuidesIndexRoute: ContentGuidesIndexRoute,
}

const ContentRouteWithChildren =
  ContentRoute._addFileChildren(ContentRouteChildren)

interface ProtectedRouteChildren {
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedSettingsRoute: ProtectedSettingsRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentRoute: ContentRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
