/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// It will be regenerated when the dev server is started.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SignInRouteImport } from "./routes/sign-in";
import { Route as SignUpRouteImport } from "./routes/sign-up";
import { Route as ProtectedRouteImport } from "./routes/_protected";
import { Route as ProtectedSettingsRouteImport } from "./routes/_protected/settings";

const rootRoute = rootRouteImport.update({
  id: "__root__",
} as const);

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as const);

const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRoute,
} as const);

const SignUpRoute = SignUpRouteImport.update({
  id: "/sign-up",
  path: "/sign-up",
  getParentRoute: () => rootRoute,
} as const);

const ProtectedRoute = ProtectedRouteImport.update({
  id: "/_protected",
  getParentRoute: () => rootRoute,
} as const);

const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: "/_protected/settings",
  path: "/settings",
  getParentRoute: () => ProtectedRoute,
} as const);

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  SignInRoute,
  SignUpRoute,
  ProtectedRoute: ProtectedRoute.addChildren({ ProtectedSettingsRoute }),
});

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/sign-in": {
      id: "/sign-in";
      path: "/sign-in";
      fullPath: "/sign-in";
      preLoaderRoute: typeof SignInRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/sign-up": {
      id: "/sign-up";
      path: "/sign-up";
      fullPath: "/sign-up";
      preLoaderRoute: typeof SignUpRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/_protected": {
      id: "/_protected";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof ProtectedRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/_protected/settings": {
      id: "/_protected/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof ProtectedSettingsRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
  }
}
